"""Pydantic models for section structure extraction output."""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, field_validator


class SubTitleItem(BaseModel):
    """Level-2 subtitle entry under a section."""

    model_config = ConfigDict(extra="allow")

    title: str = ""
    figures: List[str] = Field(default_factory=list)
    tables: List[str] = Field(default_factory=list)
    line_number: Optional[int] = None

    @field_validator("figures", "tables", mode="before")
    @classmethod
    def _coerce_str_list(cls, value: object) -> List[str]:
        if value is None:
            return []
        if isinstance(value, list):
            return [str(v) for v in value if v is not None]
        return [str(value)]


class SectionItem(BaseModel):
    """Top-level section item generated by the section extraction prompt."""

    model_config = ConfigDict(extra="allow")

    title: str = ""
    level: int = 0
    sub_level: Optional[int] = None
    sub_title_list: List[SubTitleItem] = Field(default_factory=list)
    figures: List[str] = Field(default_factory=list)
    tables: List[str] = Field(default_factory=list)
    is_reference: int = 0
    is_appendix: int = 0
    is_body: int = 0
    line_number: Optional[int] = None
    text_content: Optional[str] = None

    @field_validator("figures", "tables", mode="before")
    @classmethod
    def _coerce_str_list(cls, value: object) -> List[str]:
        if value is None:
            return []
        if isinstance(value, list):
            return [str(v) for v in value if v is not None]
        return [str(value)]

    @field_validator("sub_title_list", mode="before")
    @classmethod
    def _coerce_subtitles(cls, value: object) -> List[object]:
        if value is None:
            return []
        if isinstance(value, list):
            return value
        return [value]


class SectionList(RootModel[List[SectionItem]]):
    """Root list model for section extraction output."""
